// Tableau de 100 affirmations positives
const affirmations = [
    "Je suis capable de réaliser tout ce que je désire.",
    "Je mérite d'être heureux et comblé.",
    "Je suis une personne positive et pleine d'énergie.",
    "Je fais confiance à mes capacités.",
    "Je m'aime et m'accepte tel que je suis.",
    "Je suis digne d'amour et de respect.",
    "Je prends soin de mon corps, de mon esprit et de mon âme.",
    "Je crois en moi et en mes rêves.",
    "Chaque jour est une nouvelle opportunité de grandir.",
    "Je suis reconnaissant pour tout ce que la vie m'apporte.",
    // Ajoutez ici plus d'affirmations, jusqu'à en avoir 100
    "Je suis une personne créative et pleine de ressources.",
    "Je fais des choix alignés avec mes valeurs.",
    "Je suis entouré de personnes qui me soutiennent.",
    "Je suis confiant dans mes décisions.",
    "Je suis une source de lumière pour les autres.",
    "Je mérite le succès dans tout ce que je fais.",
    "Je suis en paix avec moi-même et le monde qui m'entoure.",
    "Je m'ouvre à de nouvelles opportunités chaque jour.",
    "Je suis en parfaite harmonie avec l'univers.",
    "Je suis un être de valeur et je mérite tout ce qui est bon.",
    "Je suis capable de surmonter tous les défis.",
    "Je choisis de voir le bien dans chaque situation.",
    "Je suis calme, détendu et centré.",
    "Je suis une personne forte et résiliente.",
    "J'attire le succès dans ma vie.",
    "Je vis dans l'abondance et la prospérité.",
    "Je suis une personne aimante et bienveillante.",
    "Je fais confiance au processus de la vie.",
    "Je suis fier de moi et de mes réalisations.",
    "Je rayonne de confiance et de positivité.",
    "Je choisis d'être heureux ici et maintenant.",
    "Je suis en contrôle de mes pensées et de mes émotions.",
    "Je m'accorde le droit de faire des erreurs et d'apprendre.",
    "Je suis en pleine forme physique et mentale.",
    "Je suis une personne inspirante pour les autres.",
    "Je mérite d'être épanoui dans tous les domaines de ma vie.",
    "Je suis reconnaissant pour chaque petit bonheur.",
    "Je suis capable de tout accomplir avec confiance et clarté.",
    "Je suis toujours en train de grandir et d'évoluer.",
    "Je suis entouré d'amour et de soutien.",
    "Je suis ouvert aux changements positifs dans ma vie.",
    "Je suis le créateur de ma propre réalité.",
    "Je suis une personne aimable et aimante.",
    "Je suis libre de toute peur et de tout doute.",
    "Je mérite de vivre une vie épanouissante.",
    "Je suis rempli de joie et de gratitude.",
    "Je crois en mon pouvoir de transformation.",
    "Je suis connecté à mon potentiel infini.",
    "Je suis en sécurité et tout va bien.",
    "Je suis exactement là où je dois être.",
    "Je m'accepte entièrement et sans réserve.",
    "Je suis capable de surmonter toutes les difficultés.",
    "Je suis une personne courageuse et déterminée.",
    "Je suis entouré d'énergie positive.",
    "Je fais confiance à mon intuition.",
    "Je suis en harmonie avec moi-même.",
    "Je m'aime et je suis aimé.",
    "Je suis maître de mon bonheur.",
    "Je vis dans le moment présent et je savoure chaque instant.",
    "Je suis une personne authentique et vraie.",
    "Je suis guidé par la sagesse intérieure.",
    "Je suis libre d'être moi-même.",
    "Je suis une personne créative et pleine d'imagination.",
    "Je mérite tout ce qu'il y a de meilleur dans la vie.",
    "Je suis en paix avec mon passé.",
    "Je suis capable d'atteindre tous mes objectifs.",
    "Je suis rempli d'énergie et de vitalité.",
    "Je suis reconnaissant pour la beauté de chaque jour.",
    "Je suis une personne aimable et gentille.",
    "Je suis le maître de ma vie et de mon destin.",
    "Je suis un être unique et spécial.",
    "Je fais confiance à la vie et à ses mystères.",
    "Je suis en paix avec moi-même et mon environnement.",
    "Je suis responsable de ma propre joie.",
    "Je choisis d'être optimiste et positif.",
    "Je suis une personne bienveillante et empathique.",
    "Je suis un aimant à bonnes choses.",
    "Je mérite d'être apprécié pour ce que je suis.",
    "Je m'entoure de personnes positives et inspirantes.",
    "Je vis une vie pleine de sens et de bonheur.",
    "Je suis fier de qui je suis aujourd'hui.",
    "Je suis un être d'amour et de lumière.",
    "Je suis capable de changer ma réalité.",
    "Je suis une personne intuitive et inspirée.",
    "Je suis prêt à accueillir le succès dans ma vie.",
    "Je suis une personne honnête et intègre.",
    "Je suis entouré de beauté et d'abondance.",
    "Je suis un être créatif, libre et épanoui.",
    "Je fais de mon mieux chaque jour.",
    "Je suis une personne calme et posée.",
    "Je suis prêt à recevoir tout le bien de la vie.",
    "Je suis un être spirituel en constante évolution.",
    "Je suis connecté à la source de l'amour universel."
];

// Fonction pour générer une affirmation positive
function generateAffirmation() {
    const randomIndex = Math.floor(Math.random() * affirmations.length);
    document.getElementById('affirmation').innerText = affirmations[randomIndex];
}
